/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pdftoexcel

fun main() {
    val converter = PdfConverter()

//    converter.convertWithSpire()

    converter.convertWithAspose()
}
