/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("project.structure.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

dependencies {
    implementation("org.springframework.data:spring-data-commons:3.0.0")
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")

    implementation("com.querydsl:querydsl-jpa:5.0.0:jakarta")
    implementation("com.querydsl:querydsl-core:5.0.0")
    kapt("com.querydsl:querydsl-apt:5.0.0:jakarta")
}
