version: '3.8'

services:
  redis-master:
    image: redis:6.2.6
    container_name: redis-master
    ports:
      - "6379:6379"
    entrypoint: ["redis-server", "--maxmemory", "1403mb", "--maxmemory-policy", "volatile-lru"]
    networks:
      - redis-network

  redis-replica:
    image: redis:6.2.6
    container_name: redis-replica
    depends_on:
      - redis-master
    entrypoint: ["redis-server", "--replicaof", "redis-master", "6379", "--maxmemory", "256mb", "--maxmemory-policy", "volatile-lru"]
    ports:
      - "6380:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
