/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("project.structure.kotlin-application-conventions")
}

dependencies {
    implementation(project(":library"))
}

application {
    // Define the main class for the application.
    mainClass.set("project.structure.admin.AdminApiApplication.kt")
}
