spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/testdb
      username: postgres
      password: password
  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    properties:
      org.quartz.jobStore.isClustered: true
      org.jobStore.dataSource=quartzDataSource: quartzDataSource
      org.quartz.jobStore.clusterCheckinInterval: 20000
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.scheduler.instanceName: simple
      org.quartz.scheduler.instanceId: AUTO
  h2:
    console:
      enabled: true
